server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    path(route='about', view=views.about, name='about'),

    path(route='contact', view=views.contact, name='contact'),

    path(route='registration', view=views.registration_request, name='registration'),

    path(route='login', view=views.login_request, name='login'),

    path(route='logout', view=views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    path('dealer/<int:dealer_id>/',
         view=views.get_dealer_details, name='dealer_details'),

    path('review/<int:dealer_id>/',
         view=views.add_review, name='add_review'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


class CarModel(models.Model):
    SEDAN = 'sedan'
    SUV = 'suv'
    WAGON = 'wagon'
    CAR_TYPES = [
        (SEDAN, 'Sedan'),
        (SUV, 'Suv'),
        (WAGON, 'Wagon')
    ]
    make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    name = models.CharField(null=False, max_length=50)
    dealer_id = models.IntegerField()
    car_type = models.CharField(max_length=50, choices=CAR_TYPES)
    year = models.DateField()

    def __str__(self):
        return "Name: " + self.name + "," + \
                "Dealer ID: " + str(self.dealer_id) + "," + \
               "Type: " + self.car_type + "," + \
               "Year: " + str(self.year.year)


class CarDealer:
    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name


class DealerReview:
    def __init__(self, dealership, name, purchase, review, purchase_date, car_make, car_model, car_year,sentiment, id):
        self.dealership=dealership
        self.name=name
        self.purchase=purchase
        self.review=review
        self.purchase_date=purchase_date
        self.car_make=car_make
        self.car_model=car_model
        self.car_year=car_year
        self.sentiment=sentiment #Watson NLU service
        self.id=id

    def __str__(self):
        return "Review: " + self.review +\
                " Sentiment: " + self.sentiment

server/djangoapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, get_dealer_from_cf_by_id, post_request
from django.contrib.auth import login, logout, authenticate
import logging
from datetime import datetime
from .models import CarModel

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


def about(request):
    return render(request, 'djangoapp/about.html')


def contact(request):
    return render(request, 'djangoapp/contact.html')


def login_request(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(to=reverse('admin:index'))
        else:
            return redirect('djangoapp:index')


def logout_request(request):
    logout(request)
    return redirect('djangoapp:index')


def registration_request(request):
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)


def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://e29b86ca.eu-gb.apigw.appdomain.cloud/api/dealership"
        dealerships = get_dealers_from_cf(url)
        context["dealership_list"] = dealerships
        return render(request, 'djangoapp/index.html', context)


def get_dealer_details(request, dealer_id):
    if request.method == "GET":
        context = {}
        url = "https://e29b86ca.eu-gb.apigw.appdomain.cloud/api/review/"
        reviews = get_dealer_reviews_from_cf(url, dealer_id)
        context["reviews"] = reviews
        dealer = get_dealer_from_cf_by_id(
            "https://e29b86ca.eu-gb.apigw.appdomain.cloud/api/dealership", dealer_id)
        context["dealer"] = dealer
        return render(request, 'djangoapp/dealer_details.html', context)


def add_review(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = "https://e29b86ca.eu-gb.apigw.appdomain.cloud/api/dealership"
        dealer = get_dealer_from_cf_by_id(url, dealer_id)
        cars = CarModel.objects.filter(dealer_id=dealer_id)
        context["cars"] = cars
        context["dealer"] = dealer
        return render(request, 'djangoapp/add_review.html', context)

    if request.method == "POST":
        url = "https://e29b86ca.eu-gb.apigw.appdomain.cloud/api/review/"      
        if 'purchasecheck' in request.POST:
            was_purchased = True
        else:
            was_purchased = False
        cars = CarModel.objects.filter(dealer_id=dealer_id)
        for car in cars:
            if car.id == int(request.POST['car']):
                review_car = car  
        review = {}
        review["time"] = datetime.utcnow().isoformat()
        review["name"] = request.POST['name']
        review["dealership"] = dealer_id
        review["review"] = request.POST['content']
        review["purchase"] = was_purchased
        review["purchase_date"] = request.POST['purchasedate']
        review["car_make"] = review_car.make.name
        review["car_model"] = review_car.name
        review["car_year"] = review_car.year.strftime("%Y")
        json_payload = {}
        json_payload["review"] = review
        response = post_request(url, json_payload)
        return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review - About</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'djangoapp:index' %}"
        >Dealership Review</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="ml-auto">
          <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
          <a href="{% url 'djangoapp:logout' %}">Log out</a>
        </div>
        {% else %}
        <form
          class="form-inline ml-auto"
          action="{% url 'djangoapp:login' %}"
          method="post"
        >
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Username"
            name="username"
            required
          />
          <input
            class="form-control mr-sm-2"
            type="password"
            placeholder="Password"
            name="psw"
            required
          />
          <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">
            Login
          </button>
          <a
            class="btn btn-outline-primary my-2 my-sm-0"
            href="{% url 'djangoapp:registration' %}"
            >Sign Up</a
          >
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="jumbotron">
      <h1 class="text-center mb-5">
        Welcome to Best Cars dealership, home to the best cars in North America.
        <br />
        We sell domestic and imported cars at reasonable prices.
      </h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.
      </p>
    </div>
    <div style="min-height: 500px" class="text-center">
      <img
        src="{{MEDIA_URL}}/dealership.jpg"
        style="max-width: 710px; height: auto"
      />
    </div>
    <footer class="bg-light text-center text-lg-start mt-5">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022
        <a class="text-dark" href="{% url 'djangoapp:index' %}"
          >Dealership Review</a
        >
      </div>
    </footer>
  </body>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'djangoapp:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
                </li>
              </ul>
            </div>
          </nav>
          <div style="min-height: 190px"></div>
          <div class="container">
            <div class="row">
                <div class="col-md">
                    <h4 class="mb-5"> Add a review for <strong>{{dealer.full_name}}</strong></h4>
                    <form action = "{% url 'djangoapp:add_review' dealer.id %}" method="post">
                        <H5>Your Name:</H5><br>
                        {% csrf_token %}
                        <input class="form-control" id="name" name="name" size="30" required></textarea><br>
                        <H5>Enter the review content:</H5><br>
                        <textarea class="form-control" id="content" name="content" rows="2" required></textarea><br>
                        <div class = "form-check mt-5">
                            <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                            <label class="form-check-label">Has purchased car from {{dealer.full_name}} ?<label> <span style="color: gray; font-weight: 300; padding-left: 5px;">(select purchased car information below if checked)</span>
                        </div>
                        <div class="d-flex mt-3">
                            <div class="mr-5">
                                <h5>Select your car (model-make-year):</h5><br/>
                                <select name="car" id="car" class="form-select"><br>
                                    {% for car in cars %}
                                        <option selected value={{car.id}}>{{car.name}}-{{car.car.name}}-{{ car.year|date:"Y" }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div>
                                <h5>Select Your Purchase Date:</h5><br/>
                                <div class = "input-group date" data-provide="datepicker-inline"> 
                                    <input class="date-own form-control" type="date" name="purchasedate" id="purchasedate"><br>
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-primary mt-5" type="submit">Add review</button>
                    </form>
                </div>
            </div>
          </div>
          <div style="min-height: 200px"></div>
          <footer class="bg-light text-center text-lg-start mt-5">
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
              © 2022
              <a class="text-dark" href="{% url 'djangoapp:index' %}"
                >Dealership Review</a
              >
            </div>
          </footer>
    </body>
    <script type="text/javascript">
        $('.date-own').datepicker({
           format: 'mm/dd/yyyy'
         });
   </script>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review - Contact</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>

  <body class="vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'djangoapp:index' %}"
        >Dealership Review</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="ml-auto">
          <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
          <a href="{% url 'djangoapp:logout' %}">Log out</a>
        </div>
        {% else %}
        <form
          class="form-inline ml-auto"
          action="{% url 'djangoapp:login' %}"
          method="post"
        >
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Username"
            name="username"
            required
          />
          <input
            class="form-control mr-sm-2"
            type="password"
            placeholder="Password"
            name="psw"
            required
          />
          <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">
            Login
          </button>
          <a
            class="btn btn-outline-primary my-2 my-sm-0"
            href="{% url 'djangoapp:registration' %}"
            >Sign Up</a
          >
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="container mt-5">
      <div class="col-md-4">
        <address>
          <strong>Dealership Review Inc.</strong><br />
          1234 Example Street<br />
          Antartica, Example 0987<br />
          <a href="mailto:#">exam.ple@example.com</a>
        </address>
      </div>
    </div>
    <div style="min-height: 725px"></div>
    <footer class="bg-light text-center text-lg-start mt-5">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022
        <a class="text-dark" href="{% url 'djangoapp:index' %}"
          >Dealership Review</a
        >
      </div>
    </footer>
  </body>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
  </head>

  <body class="vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'djangoapp:index' %}"
        >Dealership Review</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:index' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="ml-auto">
          <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
          <a class="btn btn-link" method= "GET" href="{% url 'djangoapp:add_review' dealer.id %}">Add review</a>
          <a href="{% url 'djangoapp:logout' %}">Log out</a>
        </div>
        {% else %}
        <form
          class="form-inline ml-auto"
          action="{% url 'djangoapp:login' %}"
          method="post"
        >
          {% csrf_token %}
          <input
            class="form-control mr-sm-2"
            type="text"
            placeholder="Username"
            name="username"
            required
          />
          <input
            class="form-control mr-sm-2"
            type="password"
            placeholder="Password"
            name="psw"
            required
          />
          <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">
            Login
          </button>
          <a
            class="btn btn-outline-primary my-2 my-sm-0"
            href="{% url 'djangoapp:registration' %}"
            >Sign Up</a
          >
        </form>
        {% endif %}
      </div>
    </nav>

    <div class="container mt-5">
      <div class="rows">
        <div class="col-md mb-5">
          <h3>Reviews for <strong>{{ dealer.full_name }}</strong></h3>
        </div>
        <div class="col-md">
          {% if reviews %}
          <div class="card-columns">
            {% for review in reviews %}
            <div class="card">
              {% if review.sentiment == 'positive' %}
              <img
                class="card-img-left"
                src="{{MEDIA_URL}}/emoji/positive.png"
                style="width: 30px; height: 30px"
              />
              {% endif %} {% if review.sentiment == 'neutral' %}
              <img
                class="card-img-left"
                src="{{MEDIA_URL}}/emoji/neutral.png"
                style="width: 30px; height: 30px"
              />
              {% endif %} {% if review.sentiment == 'negative' %}
              <img
                class="card-img-left"
                src="{{MEDIA_URL}}/emoji/negative.png"
                style="width: 30px; height: 30px"
              />
              {% endif %}

              <div class="card-body bg-light">
                {% if review.car_make %}
                <h5 class="card-title">{{review.car_make}}, {{review.car_model}}</h5>
                <h5 class="card-title">{{review.car_year}}</h5>
                {% else %} 
                <h5 class="card-title">Reviewer did not buy any car.</h5>
                <h5 class="card-title" style="color: #f8f9fa;">.</h5>
                {% endif %}
                </h5>
                <label class="card-title">{{review.review}} </label>
              </div>
            </div>
          {% endfor %}
          {% else %}
          <div class="card-columns">
            <div class="card">
              <div class="card-body bg-light">
                <h5 class="card-title">No reviews yet</h5>
                <a class="btn btn-link" method= "GET" href="{% url 'djangoapp:add_review' dealer.id %}">Be first to add a review?</a>
              </div>
            </div>
          </div>
          {% endif %}
          </div>
        </div>
      </div>
      {% if reviews %}
      <div style="min-height: 560px"></div>
      {% else %}
      <div style="min-height: 625px"></div>
      {% endif %}
    </div>
    <footer class="bg-light text-center text-lg-start mt-5">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022
        <a class="text-dark" href="{% url 'djangoapp:index' %}"
          >Dealership Review</a
        >
      </div>
    </footer>
  </body>
</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body class="vh-100">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Dealership Review</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'djangoapp:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact</a>
                </li>
              </ul>
              {% if user.is_authenticated %}
              <div class="ml-auto">
                <span class="mr-2">{{ user.first_name }}({{ user.username }})</span>
                <a href="{% url 'djangoapp:logout' %}">Log out</a>
              </div>
              {% else %}
              <form class="form-inline ml-auto" action="{% url 'djangoapp:login' %}" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" placeholder="Username" name="username" required>
                <input class="form-control mr-sm-2" type="password" placeholder="Password" name="psw" required>
                <button class="btn btn-primary my-2 my-sm-0 mr-2" type="submit">Login</button>
                <a class="btn btn-outline-primary my-2 my-sm-0"  href="{% url 'djangoapp:registration' %}">Sign Up</a>
              </form>
              {% endif %}
            </div>
          </nav>

          <main role="main" class="container pt-3">
            <h1 class="mt-2 mb-4">Dealerships</h1>
            <table class="table" id="table" data-filter-control="true">
                <thead>
                    <tr>
                        <th data-field="id">ID</th>
                        <th data-field="full_name">Dealership Name</th>
                        <th data-field="city">City</th>
                        <th data-field="address">Address</th>
                        <th data-field="zip">ZIP Code</th>
                        <th data-field="state" data-filter-control="select">State</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for dealer in dealership_list %}
                        <tr>
                            <td>{{dealer.id}}</td>
                            <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                            <td>{{dealer.city}}</td>
                            <td>{{dealer.address}}</td>
                            <td>{{dealer.zip}}</td>
                            <td>{{dealer.st}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>

    <footer class="bg-light text-center text-lg-start mt-5">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2022 <a class="text-dark" href="{% url 'djangoapp:index' %}">Dealership Review</a>
        </div>
      </footer>
    </body>

    <script>
        $(function() {
          $('#table').bootstrapTable()
        })
      </script>
</html>